### ISSUE TITLE
Eski eşya panelden değiştirilip onaylanamıyor

### ISSUE THREAD

**Issue by aysuuu** [EsyaKutuphanesi/esyakutuphanesi#100]
Admin panelinden, eskiden paylaşılmış olan eşyalardan birinin kategorisini değiştirmeye ve onaylamaya çalıştım. Edit tuşuna basınca 502 Bad Gateway hatası aldım.
Eşyayı filtre ile buldum, hatayı aldığımda filtre etkindi.

**Comment by aysuuu** [comment]
@didemyeni @umutcan buna bir göz atabilir misiniz? Onay bekleyen eski eşyalar var, onları başka nasıl onaylayıp editleyebiliriz? (eşya kategorileri yanlış)

**Comment by umutcan** [comment]
Tam olarak nedenini anlamadığım garip bir hata vardı. Adres ile bağlantılı tüm ekranları etkiliyordu. Sadece eskilerle ilişkili bir durum değilmiş. Düzeldi şimdi.
