### ISSUE TITLE
Rozet, Kartpostal ve Magnet için satış sayfası

### ISSUE THREAD

**Issue by aysesya** [EsyaKutuphanesi/esyakutuphanesi#101]
Yalınlığın bir adım ötesinde (bizi destekle butonunda hareket de olmadığından bir deneme daha niyetine) rozeti, kartpostalı, magneti ve belki "gelip evine listelemeye yardım ederiz" servisi gibi servisleri satışa sunabileceğimiz bir sayfa eklesek?

**Comment by umutcan** [comment]
@aysesya sayfanın içeriği nasıl olacak?

**Comment by aysesya** [comment]
direk bir satış sayfası gibi rozet resmi, ücreti, satın al butonu?

**Comment by umutcan** [comment]
Herhangi bir ödeme sistemi ile entegrasyon gerekir o buton için. Paypal sanırım göreceli olarak kolay ama o bile zaman alır. Bizim kodlara böyle bir şeyi entegre etmekle uğraşmak yerine Etsy, eBay gibi kanallara yönlendirip orada deneme yapmak daha mı iyi olur acaba şu aşamada? Rozet, magnet gibi şeyler için geçerli bu. Hizmet vermeyi kastetmiyorum.

**Comment by aysuuu** [comment]
Etsy ve eBay'e yönlendirme fazla dolaylı bir yol. Oradan alışveriş edebilmek için onlara üye olması gerekecek bu sefer de kişinin. Eninde sonunda bir gün online ödeme sistemi entegrasyonu gerekecek, ben şimdiden bu vesileyle deneyelim, öğrenelim derim.

**Comment by aysuuu** [comment]
Etsy ve eBay'e yönlendirme fazla dolaylı bir yol. Oradan alışveriş edebilmek için onlara üye olması gerekecek bu sefer de kişinin. Eninde sonunda bir gün online ödeme sistemi entegrasyonu gerekecek, ben şimdiden bu vesileyle deneyelim, öğrenelim derim.

**Comment by aysuuu** [comment]
Etsy ve eBay'e yönlendirme fazla dolaylı bir yol. Oradan alışveriş edebilmek için onlara üye olması gerekecek bu sefer de kişinin. Eninde sonunda bir gün online ödeme sistemi entegrasyonu gerekecek, ben şimdiden bu vesileyle deneyelim, öğrenelim derim.

**Comment by aysuuu** [comment]
Etsy ve eBay'e yönlendirme fazla dolaylı bir yol. Oradan alışveriş edebilmek için onlara üye olması gerekecek bu sefer de kişinin. Eninde sonunda bir gün online ödeme sistemi entegrasyonu gerekecek, ben şimdiden bu vesileyle deneyelim, öğrenelim derim.

**Comment by umutcan** [comment]
Dolaylı olması konusunda haklısın. O zaman Paypal  ile böyle bir şeyler yapmak üzere planlayabiliriz. SanalPOS sistemlerinde bir çok bürokrasi var.

**Comment by aysesya** [comment]
Bence "satın al"a tıkladığında banka hesap numaramız yazılı bir ekran çıksa bile olur :) En azından kaç kişi tıklamış ve kaç kişi hesap numarasına para yatırmamak için vazgeçmiş onu görmek bile bana iyi gelir :) Bu şekilde sayfada dururken de arkadan PayPal işine bakar oluruz..

**Comment by aysuuu** [comment]
@aysesya :+1:

**Comment by didemyeni** [comment]
@aysesya +1 :) o zaman sen sayfanın yerleşimi vb. için bişiler çiziktirip paylaşır mısın bizimle?

**Comment by didemyeni** [comment]
şimdiki destekle sayfası yeterli miydi bunun için yoksa başka bişi mi arıyoruz? eğer okeyse kapatalım. @aysesya

**Comment by didemyeni** [comment]
bunu kapıyorum. zaten turgay la üzerinden geçicez.
