### ISSUE TITLE
Ödünç istenme süresinde karışıklık

### ISSUE THREAD

**Issue by aysuuu** [EsyaKutuphanesi/esyakutuphanesi#103]
Aranılan bir eşya listelendiğinde, ödünç süresini eşyayı verecek kişi belirliyor, ancak sonra mesajlaşmada 'Ödünç istenme süresi: ... gün' olarak gözüküyor.

Mantıkken eşyayı kullanacak kişinin bu süreyi belirlemesi gerek. Aranan eşya listeleme formunda değişiklik yapılmalı ve ödünç istenme süresi ve hatta belirli bir günden itibaren isteniyorsa onun için yer olmalı - ödünç başlangıç zamanı: Önemsiz ya da seçilebilen gün gibi.

**Comment by umutcan** [comment]
#41'de aynı şeyi konuştuk sanki.
