### ISSUE TITLE
Aranılan eşyaya resim eklenebiliyor

### ISSUE THREAD

**Issue by aysuuu** [EsyaKutuphanesi/esyakutuphanesi#104]
Şu anda aranılan eşya ilk kez listelenirken resim ekleme özelliği yok. Ancak daha sonra 'Eşya Kütüphanem'e giderek eşya düzenlenirse resim eklenebiliyor.

Aranan eşyada resim özelliği ya tümden kalksın, ya da her yerden resim eklenebilir olsun.

Ben aranan/listelenmiş eşya farkı daha net ortaya konmadığı sürece resim eklenemez olmasından yanayım.

**Comment by umutcan** [comment]
Bence de su an eklenmemesi daha mantıklı.

**Comment by aysuuu** [comment]
Kuzum ne ekledin/çıkardın, onu da yazsan ya buraya :)

**Comment by didemyeni** [comment]
şu yukarda "closed this in ..." diyo ya, ordan görüntüleniyor kodlar. onu mu sordun yoksa hata ne diye mi? hatayı yazıyım hemencik burdan, önceden eşyanın aranıp aranmadığı kullanıcı paylaşırken seçiyordu ya, hala o koddan alıyormuş aranılıyor mı paylaşılıyor mu verisini. şimdi seçtirmediğimiz için defaultta paylaşılıyor gibi geliyormuş düzenle sayfasına.
