### ISSUE TITLE
Üst bar - ribbon içeriğini değiştirelim mi?

### ISSUE THREAD

**Issue by aysesya** [EsyaKutuphanesi/esyakutuphanesi#110]
Üst bardaki arama kısmını çıkarsak da orayı doğru düzgün menü gibi yapsak? Denesek en azından? :)
http://bisikletlisahaf.com gibi? 

Nedir? // Biz Kimiz? // Basında Biz // Destek ol // SSS // Blog // Ağlarımız // İletişim

@didemyeni analyticsten üst bar arama bandı kullanım oranını görebiliyor muyduk? Bir de "Basında Biz" vs tıklamalarını görmüş oluruz. Bunu A/B test olarak da yapabiliriz dilerseniz?

**Comment by ulgens** [comment]
Benden :+1:  Ama arama ve kişisel menüyü napacağız?

**Comment by aysesya** [comment]
Dropdown menü olabilir kişisel menü için (bkz. resim). Arama barını üst bardan kaldırmayı oylamak istiyorum :) Çoğunluk bu bar değiştirmeye ok derse hemen bi prototip çizeyim diye soru olarak açtım..

![profil](https://cloud.githubusercontent.com/assets/8343249/6526553/d63f4192-c41b-11e4-8030-485d1323a4c1.PNG)

**Comment by aysuuu** [comment]
4 gün önce miii? Ben niye görmedim yahu bunu? Benden de :+1:

**Comment by didemyeni** [comment]
Hello! http://app.vwo.com/#/campaign/2/preview şurdan yapabilirsin @aysesya  değişiklikleri. (ben biraz düzelttim ama sıralamasını pek sevmedim :)) Sonra da tamam dersek koda alırız.

**Comment by didemyeni** [comment]
değiştirdikdi zaten. kapıyorum.
