### ISSUE TITLE
Eşya paylaş sayfasına uyarı ekleme

### ISSUE THREAD

**Issue by aysuuu** [EsyaKutuphanesi/esyakutuphanesi#112]
Eşya listeleme sayfasına, 'sadece ödünç eşyaları onaylıyoruz, hibe DEĞİL!' gibi bir uyarı yazalım.

Ek olarak hibe olarak paylaşılanlara admin panelinde hibe butonu olsa ve otomatik e-posta gitse çok güzel olur. 

Ne dersiniz?

**Comment by didemyeni** [comment]
eşya listelemeye ekledim bunu. panele de butonu ekledim.
