### ISSUE TITLE
Ödünç iste pop-up'ında mesaj yaz alanı boş ve zorunlu olsun

### ISSUE THREAD

**Issue by aysesya** [EsyaKutuphanesi/esyakutuphanesi#113]
Ödünç iste'ye tıkladığımda açılan pop-up alanında otomatik yazılı metin olmasa ve doldurmak zorunlu olsa?

![image](https://cloud.githubusercontent.com/assets/8343249/6704100/c18a48f2-cd4c-11e4-94a7-447bd724d8f4.png)

**Comment by aysuuu** [comment]
:+1: bana aynı mesajlar gelince sıkılıyorum. kullanıcı olarak katılıyorum!

**Comment by ulgens** [comment]
Alanı boş ve zorunlu yapmanın sonucu "-" ya da "." mesajları olacak bence ama her şekilde hazır mesajdan iyidir.
