### ISSUE TITLE
Ödünç ver butonu sonrasında mesajlar yerine eşya paylaş sonrası gibi bir ekran çıkması

### ISSUE THREAD

**Issue by aysesya** [EsyaKutuphanesi/esyakutuphanesi#115]
Mesajın gönderildi! Cevap geldiği zaman e-postana bir bildirim gelecek. Mesaj kutuna gitmek için tıkla.
Beklerken blogumuza ya da facebook sayfamıza göz atabilirsin. 
"Bende var" dediğin bu eşyayı sitemizde de listelemek ister misin?

gibi bir mesaj yazsak?

**Comment by ulgens** [comment]
Başlığı daha kısa tutup detayı içeriğe yazsak ya. Anlamak için 3 kere okudum, doğru anladıysam destekliyorum :D

**Comment by aysesya** [comment]
:D ne bileyim başlığa da baktığınızda ne olduğunu anlayın hatırlayın diye uzun yazıyorum. Demek istediğim: Ödünç ver butonuna bastıktan sonra mesajlar ekranına geçiliyor. Bunun yerine aynı "eşya paylaş" sonrası çıkan splash ekran gibi bir ekran çıksa ve yukarıdaki metin yazda :) @didemyeni diğer ekranı yaptığı için direk o anlar diye varsaydım ;) :stuck_out_tongue_winking_eye:

**Comment by didemyeni** [comment]
ben anladım @aysesya  :)

**Comment by didemyeni** [comment]
ödünç ver ve iste işlemlerinden sonra olacak şekilde ekledim.
