### ISSUE TITLE
İletişim sayfasına minik ek

### ISSUE THREAD

**Issue by aysuuu** [EsyaKutuphanesi/esyakutuphanesi#118]
Acaba Bize Yazın:'ın hemen altına Sıkça Sorulan Sorular'a baktın mı? diye bir link atalım mı? :)
Hatta artık sitede 'Nasıl çalışır?' olacaksa ona da link verebiliriz.

http://esyakutuphanesi.com/contact

**Comment by ulgens** [comment]
Konuyu saptıracağım ama, `question` etiketine uygun şeyler bence issues'u amacından saptırmaya başladı. Bu tartışmaları Asana'da - Slack'te ya da haftalık hangoutlarda falan yapsak da karar verilen işleri buraya açsak olmaz mı, ne dersiniz?

**Comment by aysuuu** [comment]
Bugün konuyu açarsan neden olmasın? Bir hafta bekleyince ben bazen unutuyorum. Burası için küçük büyük sorun fark etmez dediğiniz için yazdım.

**Comment by ulgens** [comment]
Ben son yorumunu yeni gördüm @aysuuu . Bugün Asana'da `devel` isimli bir kanal yarattım, benim kafama takılan geliştirme odaklı konularda insanları oradan darlıyorum. `question` etiketine girecek şeyleri de oradan konuşmayı deneyebiliriz fikrimce, çıkan sonuçları da doğrudan iş olarak buraya aktarırız. Ne dersiniz?

**Comment by aysuuu** [comment]
Olur, yalnız o dediğin Asana değil Slack. Bir ara bu kullandığımız araçlarla ilgili bir blog yazısı yazsam sanırım iyi olacak - bak bu mesela Asana'lık :)

**Comment by didemyeni** [comment]
:) issue dan ayrı konular da konuşulmuş amma kapıyorum bunu. ekledim.
