### ISSUE TITLE
Destekle sayfasına ek yazı

### ISSUE THREAD

**Issue by aysuuu** [EsyaKutuphanesi/esyakutuphanesi#119]
Sayfanın en ilk paragrafına şöyle bir şey ekleyelim mi?

Eğer hala hiçbir eşyanı ödünç vermek için listelemediysen 'Eşya Paylaş'a (link) basarak oradan başlayabilirsin sitemizi kullanmaya ve dolayısıyla bize destek olmaya. Ama bu senin için yeterli değilse tabii ki başka yollar da mümkün!

http://esyakutuphanesi.com/destekle

**Comment by aysesya** [comment]
Bence hatta destekle sayfasında "bağış yap" "gönüllü ol" gibi iki ayrı başlık da koyabiliriz o yazının altına :)

**Comment by aysuuu** [comment]
Biz işletmeyiz şu anda yasal olarak, bağış alamayız!
