### ISSUE TITLE
Gönder tuşu çalışmıyor

### ISSUE THREAD

**Issue by aysuuu** [EsyaKutuphanesi/esyakutuphanesi#121]
Mobilde mesajlaşma sayfasındaki 'Gönder' tuşu çalışmıyor.

**Comment by aysuuu** [comment]
Bunu acil olarak düzeltebilir miyiz @didemyeni? Bir kullanıcımızdan tekrar şikayet geldi.

**Comment by ulgens** [comment]
Ben bunu iki branch'e göndermediğim için, çift branch çalışcaksak hotfix'ler biraz özel durum kalıyor, master'da bir değişiklik olmadı. Bugün bir kullanıcı mesajla bildirmiş durumu, ilgilisine duyurulur :)

**Comment by didemyeni** [comment]
github dan güncelledim orayı. masterda çalışman gerekirse önce pull edersin.
