### ISSUE TITLE
Anasayfada minik düzenleme

### ISSUE THREAD

**Issue by aysuuu** [EsyaKutuphanesi/esyakutuphanesi#125]
'Verilen tüm eşyalar' sanki tümden veriliyormuş hissi veriyor. Onu 'Paylaşılan tüm eşyalar' ya da 'Ödünç verilen tüm eşyalar' diye çevirsek olur mu?

**Comment by ulgens** [comment]
"Ödünç verilen" :+1:

**Comment by didemyeni** [comment]
benden de oki. yaptım.
