### ISSUE TITLE
'Ödünç verdim'e tıklayınca hata veriyor

### ISSUE THREAD

**Issue by aysuuu** [EsyaKutuphanesi/esyakutuphanesi#127]
Ödünç veren kişiden girip, ödünç istenilen bir eşya için mesajlaşma ekranından 'ödünç verdim' tıklanınca 'SAYFA BULUNAMADI' ekranına gidiyor. Bulunamayan sayfa: http://esyakutuphanesi.com/conversation/645?status=1

**Comment by didemyeni** [comment]
link değiştirme zamanınında kalmış bir link hatasıydı. kapıyorum o sebeple.
