### ISSUE TITLE
Ödünç iste çalışmıyor

### ISSUE THREAD

**Issue by aysuuu** [EsyaKutuphanesi/esyakutuphanesi#132]
Bir kullanıcımızdan gelen mesaj:
'...sitenizden ödünç istemeye çalışıyorum ama 5 gündür hata veriyor'

Kontrol ettim, 
* eşya detay sayfasından (ör: http://esyakutuphanesi.com/esya_detay/138) ödünç isteye basıp,
* çıkan popup'tan iletişime geç denilince
502 hatası veriyor.

Sanırım sunucu taşınması ile ilgili.

Hızlıca düzeltebilir misiniz @umutcan @didemyeni?

**Comment by didemyeni** [comment]
sunucu zamanı hatası. kapadım.
