### ISSUE TITLE
504 Gateway Time-out hatası

### ISSUE THREAD

**Issue by aysuuu** [EsyaKutuphanesi/esyakutuphanesi#133]
Şu anda sitede farklı sayfaları açarken bu hata ile karşılaşıyorum, sanırım sunucuya erişimde bir sorun var. Moderasyon, mesajlarım, admin şimdiye kadar deneyip bu hata ile karşılaştığım sayfalar. Moderasyon bir kere hata verip, düzeldi, diğerleri şu anda tekrarlanıyor.

@didemyeni @umutcan ADL (acil destek lütfen!) :stuck_out_tongue_winking_eye:

**Comment by umutcan** [comment]
@aysuuu bu durum sunucuya erişim ile alakalı. Kodlardaki bir durumdan kaynaklanmıyor. Neden olduğuna dair henüz iyi bir fikrim olmasa da şimdilik buranın kapsamı dışında görünüyor. O nedenle bu issue'yu kapatacağım. Eğer kodlarla ilgili bir durum çıkarsa yeniden açıp konuyla ilgili not düşebiliriz.
