### ISSUE TITLE
Aranan eşya ilanı verme butonu yok

### ISSUE THREAD

**Issue by aysuuu** [EsyaKutuphanesi/esyakutuphanesi#135]
Aranan eşya ilanı vermek için buton yok şu anda sitede. Arama barından arama yaptıktan sonra eşya bulunsa da bulunmasa da bu buton çıkmıyor.

**Comment by didemyeni** [comment]
bunu ekledim ama committe yazmayı unuttum :). o sebeple kapıyorum.
