### ISSUE TITLE
Kullanıcı onayının kaldırılması

### ISSUE THREAD

**Issue by aysuuu** [EsyaKutuphanesi/esyakutuphanesi#139]
Yeni gelen herkes direk kaydolsa, onayı kaldırsak mı? @didemyeni @aysesya

**Comment by aysesya** [comment]
Ad, Soyad, Şehir, Hobiler zorunlu alanlar olsun kayıt formunda, Nereden duydun, neden katılmak istiyorsun da zorunsuz :)
Bir de E-posta atalım tüm üyelere "Lütfen ad soyad ve şehir güncellemesi yapınız" diye. Sadece isim kullanan çok kişi var halen

**Comment by aysuuu** [comment]
@aysesya bu issue ile ilgili değil yazdıkların canımın içi. Ayrı başlık aç (kayıt formu düzeltmeleri gibi), ya da alakalı başka issue varsa, ki var, oraya yaz. Yoksa böyle serbest çağrışımla işin içinden çıkamayız :)

**Comment by aysuuu** [comment]
@aysesya @didemyeni size sorduğum soru sadece 'onayı kaldıralım mı?' idi, evet dediniz buraya yazmadınız. 

@umutcan ile bir ara yol bulundu ama yine buraya yazmadı kimse.

Değişiklik olunca yazarsanız takip açısından iyi olur @didemyeni ve hatta kapatsan hallolduysa :)

**Comment by aysesya** [comment]
Şu an kullanıcı onayını kaldırdık.
