### ISSUE TITLE
esyakutuphanesi.com paylaşımı resmi ve logo

### ISSUE THREAD

**Issue by aysuuu** [EsyaKutuphanesi/esyakutuphanesi#18]
Sitenin linkini bir Facebook grubunda paylaşınca logo yerine en son paylaşılan eşyalardan birinin resmi çıktı.
Bir de logoyu da eski haline getirsek mi acaba? Bu rengarenk fazla göz yormuyor mu? :)

**Comment by didemyeni** [comment]
şu an anasayfayı paylaşırken logo çıkıyor. açıklamasına istediğimiz seyi yazabiliriz, ya da resmi değiştirebiliriz. 
![screen shot 2015-02-09 at 16 08 12](https://cloud.githubusercontent.com/assets/1263047/6107721/e0d040e8-b075-11e4-86c0-6574227b666a.png)
