### ISSUE TITLE
Arama yapınca 502 Bad Gateway hatası veriyor

### ISSUE THREAD

**Issue by aysuuu** [EsyaKutuphanesi/esyakutuphanesi#25]
Arama barında "Eşya Ara:" kısmında Türkçe karakterli kelime girip arama yapınca "502 Bad Gateway" hatası veriyor.

**Comment by aysuuu** [comment]
Şu anda bu sorun yine var. Ayrı issue mu açmalı, yoksa reopen mı bilemedim...

**Comment by umutcan** [comment]
Aynı hata değil bu.

**Comment by umutcan** [comment]
Bad gateway  hatası herhangi bir sorun olduğunda çıkan standart hata ekranı.

**Comment by umutcan** [comment]
@aysuuu yeni bir issue açabilir misin? Bunu kapatıyorum.

**Comment by aysuuu** [comment]
tekrar edemedim hatayı, o yüzden açmıyorum.

**Comment by didemyeni** [comment]
@aysuuu ben baktım canım tamam.
