### ISSUE TITLE
Admin paneline kullanıcı onayı ile ilgili seçeneklerin eklenmesi.

### ISSUE THREAD

**Issue by aysuuu** [EsyaKutuphanesi/esyakutuphanesi#27]
Admin paneline:
1. Onayla'ya ek olarak, "Daha fazla bilgi iste", "Reddet", "Soyadını sor" gibi seçenekler eklensin.
2. Bu seçeneklerden otomatik e-postalar gitsin. - bilgi@esyakutuphanesi.com'dan gönderilip cevapların oraya alınması önemli!

**Comment by ulgens** [comment]
@aysuuu @aysesya  @didemyeni Kullanıcı onayını kaldırmak konusunda netsek bu işi kapatıyorum?
