### ISSUE TITLE
Kayıt sayfasına ek bilgi

### ISSUE THREAD

**Issue by aysuuu** [EsyaKutuphanesi/esyakutuphanesi#44]
Bir kullanıcı demiş ki:
'Uye olurken kaydımı okuyorsunuz cok sukela fakat bari on gorulen zaman verseniz 24 saat 7958 mars yili falan gibi.'

Kayıt sayfasına bildirim olarak, ya da kaydınız onay beklemektedir metnine ek olarak en geç bir hafta içerisinde geri döneceğimizi, dönmezsek bunun iyi bir şey olmadığını falan mı yazsak? Metin uzmanı tatlı dilli @aysesya ne dersin bacım?

@ulgens doğru mu şimdi bunun labelları?

**Comment by didemyeni** [comment]
ne kadar sürede geri döneceğimizi yazalım mı? 48 saat? @aysesya @aysuuu

**Comment by aysuuu** [comment]
Sistemden ortalama geridönüş zamanımızı çekebilir misin @didemyeni? Hatta hazır hesaplamışken infografiğe de koyarız ;)
