### ISSUE TITLE
Kullanıcıların kendi eşyalarını kaldırabilmelerini sağlamak

### ISSUE THREAD

**Issue by aysesya** [EsyaKutuphanesi/esyakutuphanesi#48]
Belki artık paylaşmak istemiyor, belki site dışından birisine ödünç verdi. Bize ulaşmak zorunda olmasa kaldırırken? (Bununla ilgili bir iletişim mail'ı vardı bir kullanıcıdan, oradan geldi aklıma yeniden)

**Comment by didemyeni** [comment]
eşyayı kullanıcı silebiliyor şu an, inaktif olayı yok. #107 açtım ordan devam.
