### ISSUE TITLE
Mesajlaşma iyileştirmeleri

### ISSUE THREAD

**Issue by aysuuu** [EsyaKutuphanesi/esyakutuphanesi#53]
Mesajlar ekranına
- [x] Henüz cevap verilmemiş mesajların farklı renkte gözükmesi
- [ ] İstenilen mesajların arşive atılabilmesi
- [x] En son cevap verilen ya da cevap alınan, yani bir aktivite olmuş olan mesajın en üstte durması

Mesajlaşma ekranına
- [ ] 'Vazgeç' butonunun eklenmesi - yine Zumbara gibi neden vazgeçildiği sebebi sorulup son mesaj olarak saklanılabilinir. (Bu mesaj açılınca çıkan ekrana imiş)

**Comment by didemyeni** [comment]
#105 ve #106 açtım. oradan devam edelim.
