### ISSUE TITLE
Tüm eşyaların listelenmesi

### ISSUE THREAD

**Issue by didemyeni** [EsyaKutuphanesi/esyakutuphanesi#55]
Ana sayfada tüm eşyalar görüntülenebilir. '248148921' eşya var yazalım. -sayfalandırma da olabilir.
Ana sayfada tüm eşyaların görünebileceği bir sayfaya gidilebilir..

**Comment by aysuuu** [comment]
Bunu niye kapadık?
'Paylaşılan tüm eşyaları gör' yazısı çok küçük, görünmeyen bir yerde. Geçen gün birisi 'Eskiden daha çok eşya vardı, noooldu?' dedi. Anasayfada tepeye paylaşımda olan ödünç alınabilecek eşya sayısını ve 'aranılan' eşya sayısını koyalım.

**Comment by didemyeni** [comment]
@aysuuu ekledim sayıları: http://esyakutuphanesi.com/  yerlerini ya da rengini vb. sevmezsen değiştiririz :)

**Comment by aysuuu** [comment]
Pek küçük kalmış bence diğer öğelerin yanında, ama eline sağlık canımcım. Hem bu linkleri, hem de 'Paylaşılan tüm eşyaları gör', 'Aranan tüm eşyaları gör' linklerini büyütelim derim.

Bu arada Bizi Destekle diğerlerinin yanında buton gibi durmuyor... Onun için ayrı issue mu açayım?

**Comment by aysuuu** [comment]
Sayılar tepede çok güzel de 'Paylaşılan tüm eşyaları gör', 'Aranan tüm eşyaları gör' linklerini halen çok küçük. Onları büyütmeyelim mi? @aysesya @didemyeni

**Comment by didemyeni** [comment]
bu nasıl?
![screen shot 2015-01-27 at 19 24 30](https://cloud.githubusercontent.com/assets/1263047/5923183/290ab5c6-a65a-11e4-8da5-bd9f0b1deaab.png)

**Comment by aysuuu** [comment]
Daha iyi, değil mi?

**Comment by aysuuu** [comment]
Bu arada sayılar pek güzel oldu, ellerine sağlık! :smile:
