### ISSUE TITLE
Üyelik formunun profile aktarılması

### ISSUE THREAD

**Issue by aysuuu** [EsyaKutuphanesi/esyakutuphanesi#69]
Üyelik formunda sorduğumuz soruların cevapları kullanıcı profilinde de gözüksün. Formda da bu belirtilsin ki daha net cevaplar alalım, kullanıcı da iki kez uğraşmamış olsun.

@aysesya formdaki soruları gözden geçirir misin?

**Comment by didemyeni** [comment]
başlık gerçekleştirildi :), adres ve isim soyisim alanlarını not aldım (olmadı onlar için issue açarız). ux yapılırken alınan notlara bakarız tabi ama bunu kapatıyorum.
