### ISSUE TITLE
Sayfa adreslerinin Türkçeleştirilmesi

### ISSUE THREAD

**Issue by aysuuu** [EsyaKutuphanesi/esyakutuphanesi#82]
Eski versiyonda (WP) sayfa uzantılarımız Türkçe idi, http://esyakutuphanesi.com/iletisim gibi. Şu anda http://esyakutuphanesi.com/contact gibi İngilizce olması hem bence güzel gözükmüyor, hem de Yeşilist'in haberinde (http://www.yesilist.com/cms.php?u=-1151&id=1151) olduğu gibi eski bağlantılar çalışmıyor.
Tüm sayfa uzantılarının değişmesi, Türkçe olması gerek.

**Comment by aysuuu** [comment]
v1 ne zamana çıkıyor? bu halinde hep İngilizce mi kalacak demek bu?

**Comment by ulgens** [comment]
Ben bunu bir ara tartışmaya açmıştım da havada kalmıştı diye hatırlıyorum. Linkleri tek dil yapalım evet, ama bunun Türkçe olması gerektiğine emin değilim. Türk kullanıcılar ağırlıkta dersek saygı duyarım tabi. Ek olarak, linkleri kaybetmemenin yolu linkleri değiştirmemekten değil - elbet değişecek, 301'den geçiyor.

**Comment by umutcan** [comment]
v1 işi karıştı :D Büyük bir UI/UX değişikliği planladığımız dönem şu anki halinde yapacağımız değişikler içindi o. O konudaki planlar da biraz değişmiş gibi duruyor. Doğal olarak v1 etiketi artık anlamsız gibi biraz.

Kısacası değiştirmek için bir sıkıntı yok. Dil olarak da Türkçe yapabiliriz bence. Bulunduğumuz duruma ve konuma çok daha uygun.

**Comment by aysuuu** [comment]
Şu an için yegane derdimiz Türkiye'de yayılmak ise bence tüm uzantılar Türkçe olmalı, bir an önce :)

**Comment by ulgens** [comment]
@didemyeni buna el atıyordun diye hatırlıyorum, bir aksiyon oldu mu? Boştaysa ben alıyorum. Hattaaaaa aldım! :D conflict çıkmaz umarım ama çıkarsa da eğlence olur :P

**Comment by didemyeni** [comment]
arkadaşım koddan bakarsan görürsün zati, değiştirdim ben onları. @ulgens

**Comment by ulgens** [comment]
Issue'yi niye kapatmıyorsunuz efenim o zaman? Commit mesajlarında da yoktu. Telepati geliştirmedim henüz :)

**Comment by didemyeni** [comment]
haklısın efenim valla :)

**Comment by aysuuu** [comment]
@ulgens'in atarı :+1: ahahahaha
