### ISSUE TITLE
Cevap yüzdesi doğru çalışıyor mu?

### ISSUE THREAD

**Issue by aysuuu** [EsyaKutuphanesi/esyakutuphanesi#84]
Ben bütün gelen mesajlara cevap vermişim ama %77 gözüküyor cevap yüzdem. Neden acaba?
http://esyakutuphanesi.com/profile/1004

**Comment by didemyeni** [comment]
alla alla. gelen isteklere yanıt verdiyse 100 olmalı bu. mesajlaşmanın devamını kontrol etmiyoruz. yalnızca gelen ödünç isteme/vermeye yanıt verilmiş mi ona bakıyoruz. hepsine yazdığına emin misin ki @aysuuu ?

**Comment by aysuuu** [comment]
Evet cevap vermediklerim varmış:
- Biri tekrarlı mesaj, iki kez gelmiş
- İkisi iki ayrı eşyayı istemiş, tek bir eşya isteği üzerinden diyalog dönmüş...
Şimdi %100 oldu
