### ISSUE TITLE
Anasayfadan tüm eşyalara gidince yanlış bildirim

### ISSUE THREAD

**Issue by aysuuu** [EsyaKutuphanesi/esyakutuphanesi#92]
Login olmadan anasayfadan 'paylaşılan diğer eşyaları gör' ya da 'aranan diğer eşyaları gör' ile tüm eşyalara gidince 'Bu sayfaya ulaşmak için lütfen giriş yapın.' bildirimi geliyor ama sayfa görünüyor. Bildirimin kalkması lazım, ya da sayfanın açılmaması.

**Comment by didemyeni** [comment]
bununla ilgili bir sorun görmedim. template in ufak kafa karışıklıkları diyebiliriz. o sebeple kapatıyorum. eğer başka bir problem görürseniz başka bir issue açıp onun üzerinde devam ederiz.
