### ISSUE TITLE
Hibe için üye olmak isteyenlere otomatik mesaj

### ISSUE THREAD

**Issue by aysuuu** [EsyaKutuphanesi/esyakutuphanesi#94]
Hibe sebebiyle Eşya Kütüphanesi'ne üye olmak isteyenlere (Forma 'şunu şunu vermek istiyorum' yazanlara) otomatik mesaj eklesek mi? Moderasyon ekranına eklenebilir mesela.

**Comment by didemyeni** [comment]
buna @aysesya ile şöyle dedik, üye olurken değil de eşya paylaşınca eğer hibe ise ona özel e-posta atalım. admine de eklicem butonunu.

**Comment by aysuuu** [comment]
Peki. Gerçi bilinçlendirme ve UX çalışmalarında ödüncü vurgulayalım dedik. Belki dilimizde, sitemizde ödünç daha anlaşılır olursa üyelikte de azalır...

**Comment by didemyeni** [comment]
eşya paylaşanlara otomatik "bu hibe" mesajı gönderiyoruz. o sebeple kapıyorum.
