### ISSUE TITLE
Üye e-posta

### ISSUE THREAD

**Issue by didemyeni** [EsyaKutuphanesi/esyakutuphanesi#96]
üye epostalarını küçültüp alalım.

**Comment by aysuuu** [comment]
Küçültmekten kasdettiğin nedir anlamadım. Daha açık, anlaşılır olması adına (ileride de dönüp bakabiliriz bu issuelara) şöyle şöyle değil de şöyle alalım yazsan ya canımcım.

**Comment by umutcan** [comment]
@aysuuu küçük harflerle yazılmasından bahsediyor. Küçültüp almak yerine bence doğrulamaya bunu da ekleyelim. Büyük harf giremesinler.
