### ISSUE TITLE
Eşya İsteyemiyorum

### ISSUE THREAD

**Issue by aysuuu** [EsyaKutuphanesi/esyakutuphanesi#97]
5 kez Chrome'da 2 kez IE'de denedim. Büyü Dükkanı kitabı için aranıyor ilanını vermeye çalıştım, ama olmadı. Detayları doldurup 'Eşya İste'ye tıklıyorum, hiçbir hata mesajı çıkmıyor, takılı kalıyorum sayfada.

**Comment by umutcan** [comment]
#99 ile aynı nedenle oluyor muhtemelen bu da. Dışarıya yansımasa da aynı altyapıyı kullanıyorlar. Fotoğraf girilip girilmediğinin kontrolünde bu iki durum dışarıda bırakılmalı.

**Comment by aysuuu** [comment]
Halen yapamıyorum bu işlemi. Hızlı bir düzeltmesi, yaması yok mudur?

**Comment by umutcan** [comment]
Kısa bir is zaten ama kimsenin henüz bakma şansı olmadı sanırım.

**Comment by didemyeni** [comment]
benim kafam basmıo. nezle oldum :(. @umutcan dediğin gibi resim ekleme olayını bunun için yapmamak gerek. sen bakar mısın? ben bakayım mı?

**Comment by umutcan** [comment]
Hafta sonu yapabilirim ancak.

**Comment by didemyeni** [comment]
amelece biraz sanki ama yaptım :), aysu sen de bi bakıp yazarsın olup olmadığını
