### ISSUE TITLE
Yeni Fotoğraf Yüklenmiyor

### ISSUE THREAD

**Issue by ayhanerdem** [EsyaKutuphanesi/esyakutuphanesi#98]
Eşya düzenle seçilip, eşya için yeni fotoğraf seçildiğinde, fotoğraf sisteme yükleniyor gibi gözüküyor ama eşya güncellendi mesajına rağmen eski fotoğraf görüntüleniyor.

**Comment by aysuuu** [comment]
Konudan bağımsız ama tekrar hoşgeldin @ayhanerdem! @didemyeni sitenin her yerinin test edilmesini dilemişti, oluyor galiba :)

**Comment by ayhanerdem** [comment]
@aysuuu :D Hoşbulduk. :)
