### ISSUE TITLE
Fotoğraf Seçilmeden Eşya Düzenlenemiyor

### ISSUE THREAD

**Issue by ayhanerdem** [EsyaKutuphanesi/esyakutuphanesi#99]
Eşya düzenle seçilip örneğin eşyanın açıklaması değiştirildiğinde, eğer eşya fotoğrafı tekrar seçilmemişse formla gönderilen diğer bilgiler de güncellenmiyor.

**Comment by umutcan** [comment]
Fotoğraf kontrolü yapılırken kullanıcının zaten yüklü fotoğrafınının olup olmadığı kontrol edilmiyor. Muhtemelen eşya ekleme/düzenleme süreçleri yeniden düzenlenecek ama şimdilik hızlı bir çözüm olarak form doğrulaması yapılırken fotoğrafın olması da kontrol edilebilir. Varsa fotoğraf girme zorunluluğu kaldırılır.
